services:
  db:

    image: postgres:latest
    ports:
      - "5433:5433"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!

  adminer:
    image: adminer:latest
    restart: always
    ports:
     - 8888:8080